require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AbrechnungsController do

  # This should return the minimal set of attributes required to create a valid
  # Abrechnung. As you add validations to Abrechnung, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all abrechnungs as @abrechnungs" do
      abrechnung = Abrechnung.create! valid_attributes
      get :index
      assigns(:abrechnungs).should eq([abrechnung])
    end
  end

  describe "GET show" do
    it "assigns the requested abrechnung as @abrechnung" do
      abrechnung = Abrechnung.create! valid_attributes
      get :show, :id => abrechnung.id.to_s
      assigns(:abrechnung).should eq(abrechnung)
    end
  end

  describe "GET new" do
    it "assigns a new abrechnung as @abrechnung" do
      get :new
      assigns(:abrechnung).should be_a_new(Abrechnung)
    end
  end

  describe "GET edit" do
    it "assigns the requested abrechnung as @abrechnung" do
      abrechnung = Abrechnung.create! valid_attributes
      get :edit, :id => abrechnung.id.to_s
      assigns(:abrechnung).should eq(abrechnung)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Abrechnung" do
        expect {
          post :create, :abrechnung => valid_attributes
        }.to change(Abrechnung, :count).by(1)
      end

      it "assigns a newly created abrechnung as @abrechnung" do
        post :create, :abrechnung => valid_attributes
        assigns(:abrechnung).should be_a(Abrechnung)
        assigns(:abrechnung).should be_persisted
      end

      it "redirects to the created abrechnung" do
        post :create, :abrechnung => valid_attributes
        response.should redirect_to(Abrechnung.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved abrechnung as @abrechnung" do
        # Trigger the behavior that occurs when invalid params are submitted
        Abrechnung.any_instance.stub(:save).and_return(false)
        post :create, :abrechnung => {}
        assigns(:abrechnung).should be_a_new(Abrechnung)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Abrechnung.any_instance.stub(:save).and_return(false)
        post :create, :abrechnung => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested abrechnung" do
        abrechnung = Abrechnung.create! valid_attributes
        # Assuming there are no other abrechnungs in the database, this
        # specifies that the Abrechnung created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Abrechnung.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => abrechnung.id, :abrechnung => {'these' => 'params'}
      end

      it "assigns the requested abrechnung as @abrechnung" do
        abrechnung = Abrechnung.create! valid_attributes
        put :update, :id => abrechnung.id, :abrechnung => valid_attributes
        assigns(:abrechnung).should eq(abrechnung)
      end

      it "redirects to the abrechnung" do
        abrechnung = Abrechnung.create! valid_attributes
        put :update, :id => abrechnung.id, :abrechnung => valid_attributes
        response.should redirect_to(abrechnung)
      end
    end

    describe "with invalid params" do
      it "assigns the abrechnung as @abrechnung" do
        abrechnung = Abrechnung.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Abrechnung.any_instance.stub(:save).and_return(false)
        put :update, :id => abrechnung.id.to_s, :abrechnung => {}
        assigns(:abrechnung).should eq(abrechnung)
      end

      it "re-renders the 'edit' template" do
        abrechnung = Abrechnung.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Abrechnung.any_instance.stub(:save).and_return(false)
        put :update, :id => abrechnung.id.to_s, :abrechnung => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested abrechnung" do
      abrechnung = Abrechnung.create! valid_attributes
      expect {
        delete :destroy, :id => abrechnung.id.to_s
      }.to change(Abrechnung, :count).by(-1)
    end

    it "redirects to the abrechnungs list" do
      abrechnung = Abrechnung.create! valid_attributes
      delete :destroy, :id => abrechnung.id.to_s
      response.should redirect_to(abrechnungs_url)
    end
  end

end
