require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VerbindungsController do

  # This should return the minimal set of attributes required to create a valid
  # Verbindung. As you add validations to Verbindung, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all verbindungs as @verbindungs" do
      verbindung = Verbindung.create! valid_attributes
      get :index
      assigns(:verbindungs).should eq([verbindung])
    end
  end

  describe "GET show" do
    it "assigns the requested verbindung as @verbindung" do
      verbindung = Verbindung.create! valid_attributes
      get :show, :id => verbindung.id.to_s
      assigns(:verbindung).should eq(verbindung)
    end
  end

  describe "GET new" do
    it "assigns a new verbindung as @verbindung" do
      get :new
      assigns(:verbindung).should be_a_new(Verbindung)
    end
  end

  describe "GET edit" do
    it "assigns the requested verbindung as @verbindung" do
      verbindung = Verbindung.create! valid_attributes
      get :edit, :id => verbindung.id.to_s
      assigns(:verbindung).should eq(verbindung)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Verbindung" do
        expect {
          post :create, :verbindung => valid_attributes
        }.to change(Verbindung, :count).by(1)
      end

      it "assigns a newly created verbindung as @verbindung" do
        post :create, :verbindung => valid_attributes
        assigns(:verbindung).should be_a(Verbindung)
        assigns(:verbindung).should be_persisted
      end

      it "redirects to the created verbindung" do
        post :create, :verbindung => valid_attributes
        response.should redirect_to(Verbindung.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved verbindung as @verbindung" do
        # Trigger the behavior that occurs when invalid params are submitted
        Verbindung.any_instance.stub(:save).and_return(false)
        post :create, :verbindung => {}
        assigns(:verbindung).should be_a_new(Verbindung)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Verbindung.any_instance.stub(:save).and_return(false)
        post :create, :verbindung => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested verbindung" do
        verbindung = Verbindung.create! valid_attributes
        # Assuming there are no other verbindungs in the database, this
        # specifies that the Verbindung created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Verbindung.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => verbindung.id, :verbindung => {'these' => 'params'}
      end

      it "assigns the requested verbindung as @verbindung" do
        verbindung = Verbindung.create! valid_attributes
        put :update, :id => verbindung.id, :verbindung => valid_attributes
        assigns(:verbindung).should eq(verbindung)
      end

      it "redirects to the verbindung" do
        verbindung = Verbindung.create! valid_attributes
        put :update, :id => verbindung.id, :verbindung => valid_attributes
        response.should redirect_to(verbindung)
      end
    end

    describe "with invalid params" do
      it "assigns the verbindung as @verbindung" do
        verbindung = Verbindung.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Verbindung.any_instance.stub(:save).and_return(false)
        put :update, :id => verbindung.id.to_s, :verbindung => {}
        assigns(:verbindung).should eq(verbindung)
      end

      it "re-renders the 'edit' template" do
        verbindung = Verbindung.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Verbindung.any_instance.stub(:save).and_return(false)
        put :update, :id => verbindung.id.to_s, :verbindung => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested verbindung" do
      verbindung = Verbindung.create! valid_attributes
      expect {
        delete :destroy, :id => verbindung.id.to_s
      }.to change(Verbindung, :count).by(-1)
    end

    it "redirects to the verbindungs list" do
      verbindung = Verbindung.create! valid_attributes
      delete :destroy, :id => verbindung.id.to_s
      response.should redirect_to(verbindungs_url)
    end
  end

end
